# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9385c33735665f0b425227498a62410b1e05ee2e347828bed974e22f3f9963ffb267e389817ee6bce7eff99b648b99a1872657d1414f1fa110a664da251c06b6

test:
  secret_key_base: 24af3c0c7907ce93beedc475be22ea33e00e73ee1a36e58211d79928423ee5ee7bcd755917461c943a4930921fb92740141be972b9ac61e61c409f9c2837aabe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
